const validator = require("./../validators/exchangeValidator");
const { verifyToken } = require("../auth/verifyToken");
const express = require('express');
const exchangeServices = require('./../services/exchangeServices');
const router = express.Router();
router.use(validator);
router.use(verifyToken);
router.post('/files-status', exchangeServices.getFilesStatus);
router.post('/send-data', exchangeServices.uploadFileToServer);
router.get('/search', exchangeServices.search);
module.exports = router;