const validator = require("./../validators/userValidator");
const { verifyToken } = require("../auth/verifyToken");
const express = require('express');
const userServices = require('./../services/userServices');
const router = express.Router();
// router.use(validator);
router.use(verifyToken);
const multer = require("multer");
const upload = multer({ storage: multer.memoryStorage() });
router.post('/register-exchange', upload.any(), userServices.registerExchange);
router.post('/login', userServices.loginUser);
router.post('/reset-password', userServices.resetPassword);
router.get('/logout', userServices.logoutUser);
router.get('/forget-password', userServices.forgetPassword);
router.post('/send-email', userServices.sendEmail);
router.post('/send-otp', userServices.sendOtp);
router.post('/register-admin', userServices.addExchangeAdmin);
router.get('/get-exchange', userServices.getExchangeDetails);
router.get('/get-admin', userServices.getAdminDetails);
router.get('/verify-email', userServices.verifyEmail);
router.get('/verify-otp', userServices.verifyOTP);
module.exports = router;